# Generated by Django 4.2 on 2023-04-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_order_order_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_name",
            new_name="customer_name",
        ),
    ]
